#! /usr/bin/env ruby

require 'pg'

def display_help
  puts <<~HELP
    An expense recording system

    Commands:

    add AMOUNT MEMO [DATE] - record a new expense
    clear - delete all expenses
    list - list all expenses
    delete NUMBER - remove expense with id NUMBER
    search QUERY - list expenses with a matching memo field
  HELP
end

class ExpenseData
  def initialize
   @connection = PG.connect(dbname: 'expenses')
  end

  def list_expenses
    result = @connection.exec('SELECT * FROM expenses ORDER BY created_on, id;')

    result.each do |row|
      columns = [ row['id'].rjust(3), 
                  row['created_on'].rjust(10), 
                  row['amount'].rjust(12),
                  row['memo'] ]
      
      puts columns.join(' | ')
    end
  end

  def add_expenses(args)
    amount, memo, created_on = args

    abort 'You must provide an amount and memo.' unless amount =~ /^\d{1,}\.\d\d$/ && memo 
    
    created_on = created_on || Date.today

    sql = "INSERT INTO expenses(amount, memo, created_on) VALUES ($1, $2, $3);" 
    @connection.exec_params(sql, [amount, memo, created_on])  
  end
end

class CLI
  def initialize
    ed = ExpenseData.new
  end

end

ed = ExpenseData.new

case ARGV.first
when 'add'
  ed.add_expenses(ARGV[1, 3])
when 'list'
  ed.list_expenses
else
  display_help
end

